services:
  - type: web
    name: resume-analyzer
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GOOGLE_API_KEY
        value: "AIzaSyDgrWPvAAf7wXxPpKRzCtiW_h0J5DX8ce0"
